name: tabdet
channels:
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit=10.0.130
  - cudnn=7.6.0
  - pip=21.2.2
  - python=3.7.11
  - cython
  - numpy=1.21
  - poppler
  - pip:
    - jupyter==1.0.0
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - numpy==1.21.5
    - opencv-python==4.5.5.64
    - pdf2image==1.16.0
    - pypdf2==1.26.0
    - scipy==1.7.3
    - tensorflow-gpu==1.15.0
    - tensorpack==0.11
    - tqdm==4.63.0
    - git+https://github.com/philferriere/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI
